# Node image for running the application
FROM node:22.11.0

# copy the contents to the working directory
COPY ./ /frontend/

# set the working directory
WORKDIR /frontend

# download all the packages before creating the image
RUN npm install