# Node image for running the application
FROM node

# set the working directory
WORKDIR /backend

# copy the contents to the working directory
COPY * ./

# download all the packages before creating the image
RUN npm install