# Node image for running the application
FROM node:22.11.0

# copy the contents to the working directory
COPY ./ /backend/

# set the working directory
WORKDIR /backend

# download all the packages before creating the image
RUN npm install